### PR TITLE
fix(frontend): inputs styles

### PR DESCRIPTION
**Pull request by Ashe3**

### CODE REVIEW

**Review by uliana-lobanova — CHANGES_REQUESTED** [review]
You can do the same thing without using onFocus, onBlur. You can set some class to InputGroup component and in styles use [focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within) pseudo-class.

**Comment by Ashe3** [comment]
I'v already tried to fix this issue with pseudo classes. But the problem is that it doesn't work.
I'm no sure what is the reason, but ok I'll find out.

**Comment by uliana-lobanova** [comment]
@Ashe3 you can push the fix and I'll take a look and try to say what can cause a problem

**Comment by Ashe3** [comment]
Ok, I've made a changes in a frontend/src/scenes/Apps/styles.module.scss file. 
But it still not working. I think the reason is how bootstrap components are handling custom classes.

**Review by uliana-lobanova — APPROVED** [review]

**Pull request merged**
